global_options:
  dart_mappable_builder:
    runs_before:
    - retrofit_generator
    options:
      # ... other dart_mappable options
      renameMethods:
        fromJson: fromJsonString
        toJson: toJsonString
        fromMap: fromJson
        toMap: toJson
